channels:
  targets:
  - [guyer, main]
travis:
  secure:
    BINSTAR_TOKEN: F2pQr+GknUIMaY8UkqdGOfpsCC5Tp7jwX9mi3zx6Ry6zQXD9OP4wJW9R9iwveK9asur9dDjj1tpEkWRQP9R2zuf0/WxKbKEGO/LtKE0xn8NK6VuCjebsThb97w+UUH8OtJhcTH9oVLIYv1QHJyiMFinkPMes8/Bm73RU/bNkwsTRPcxG4o32u4fmHVJrQEOGk3QEIQrNvTgca734ixiHk2ImiUFhJJ95KmHV+i5uozYUNy9/CUB98P+7eWZ9shgUl6iEtPZlGOAhU3PE3Uc4RLc64E8Ucga4ayp9Zd2z/FCdzvhUM2EAEorGmUQ8lUv7/94sG5aBbllWYQu/MxWEGpLFQGX8v/+ieY4HdjXC8WclNxdbFNQP7ovmCdJaPkGoDP+fxA/OS6PxFq5pBbtSCQUQ1llcq62ZRmRe19WSkKhBv6io1cTjyVx+8aC+nGHlL0021ABxHLqESDCgvZ6XFDEf9Q2qP5fow8lPRuFblWp8EVTR+FbJfyEyvARLEmEjRCruMJoux0T+YTQNjjkc7e+sAABGNLH6B4nY8r1ZFXNkUOO3rXm46/nA1P4Zhz7XQhEaGkopmxrlOmRpPmnFuIKNaGhHT0Q53/IpHPucRBVJaQpUfXoxZCL2b8UWr40qwy66KfsUh8dIina4K6fYMyHbfbEL+4ZjLYrGnjqtvAk=
appveyor:
  secure:
    BINSTAR_TOKEN: X89+MTZivHBAXLSEy/G8CnQu+orYtiX/vKbQ7w7Wqbhv11U+EPgW+otnBaeJ6JCY
