channels:
  targets:
  - [guyer, main]
travis:
  secure:
    BINSTAR_TOKEN: CIbggRANZCndFZWKVtjnCG2lKRKXjeD4mG/3BB9cU/xbQZ4u/9MwWdYL9Fx6E/+/zq2SYim9qwLHFXtdaDmoihsZorpgnfrs2Heum1YzeNx5WNzTQxv7nkEjPsD5kWmd22tVM1CvNTOqk/oYNjkavcs32aY3BYAgBmaLhFx5h/FIswWPKtFtxFbaOh1Wqp7W4sC6ia9TaenGB1gHTcAUT0g9oJXtYgM2AohnCk868w508HRanrQAn8e5vkoVJZRw3UVG2HDVV8Nj5R3Zwd1hG3lz5P7ALTrE//uwS3p3YAmqbFHjEkjoBbaUfg+M9pWP76RIArb9WoxtF//621fnaiRQPjxbNFiCSSbTujE1+ldDQzzKIG5QZ543J2cGd2fCCcoqQl/pIvFoD7tVNqxdZOhwrqu4bk/O/96k1Z+aAy7OV8UJoVSPJ1ptcWJeXwsvMexgDYtdDa13BHOC1Oa+gsQ0loaBdOVxF/MI8OGxZkdVhZnw7zUTVkcUZovto1ddIlczfkUA0NENe0iKjkYLFrrsOMx/vihizyBL+Ct8ic0wKZq9nyqRNDBZFkz17C/SE9MTSQ3ouIZ2cZGKq9oc0gVvSDe9gXwdmQK10Bs2K2TNcdzzfuAZfotF2upj1D3UVIHNUN4zBUzDxj/zzvERk4ZgAs3p8BwHq3xB2XRY1V8=
appveyor:
  secure:
    BINSTAR_TOKEN: 26P3JkJ/iVPaW6c+5V5XYJ6H9Jaw/iYr0SU7KqDJCRk2+ScBP0rsvIyDOxDE9let
